### ISSUE TITLE
after changing grub.cfg's read/write permissions grub-editor don't launch anymore  

### ISSUE THREAD

**Issue by ghost** [Thenujan-0/grub-editor#10]
i'm using endeavourOS with KDE, and my system is mostly up to date(i update once a day), installed grub-editor from AUR using yay, it installed fine, and opened fine too, but the message to change /boot/grub/grub.cfg read/write permissions showed up, i clicked yes, i put my root password and the program closed up, and don't start anymore

trying to launch from terminal give  this

> starting main
/opt/grub-editor
Caught exception
/bin/sh: -c: line 19: syntax error near unexpected token `('
/bin/sh: -c: line 19: `ValueError: 'Windows Boot Manager (on /dev/sdb2)' is not in list'

**Comment by Thenujan-0** [comment]
Can you provide the output of the following command
`awk -F\' '$1=="menuentry " || $1=="submenu " {print i++ " : " $2}; /\tmenuentry / {print "\t" i-1">"j++ " : " $2};' /boot/grub/grub.cfg`

Also provide the value of GRUB_DEFAULT from /etc/default/grub.
And find the log file in `~/.local/share/grub-editor/logs/main.log` and provide it.

Grub editor should show an error widget with the errors in your scenario. Did it though?
If it didn't ,then the shell commands are somehow failing in your case.

The terminal output you have given looks incomplete to me. Are you sure that it is all you have gotten as output?

**Comment by ghost** [comment]
> Can you provide the output of the following command

<pre><code>0 : EndeavourOS Linux 
1 : Advanced options for EndeavourOS Linux
        1>0 : EndeavourOS Linux, with Linux linux
        1>1 : EndeavourOS Linux, with Linux linux (fallback initramfs)
2 : KDE neon 5.26 (22.04) (on /dev/sda1)
3 : Advanced options for KDE neon 5.26 (22.04) (on /dev/sda1)
        3>2 : Neon GNU/Linux (on /dev/sda1)
        3>3 : Neon GNU/Linux, with Linux 5.15.0-56-generic (on /dev/sda1)
        3>4 : Neon GNU/Linux, with Linux 5.15.0-53-generic (on /dev/sda1)
4 : Windows Boot Manager (on /dev/sdb2)
        4>5 : UEFI Firmware Settings</code></pre>

>Also provide the value of GRUB_DEFAULT from /etc/default/grub.

GRUB_DEFAULT=4
(yes, it's enter windows automatically, i chance to linux in grub)

>And find the log file in ~/.local/share/grub-editor/logs/main.log and provide it.

the file is here, but it's empty
![Screenshot_20230124_194819](https://user-images.githubusercontent.com/72302817/214438555-0bcdcb6b-5c04-48c7-ac2d-3a05379b4ff2.png)
(btw i tried to reinstall after the first bug, maybe that's why)

>Grub editor should show an error widget with the errors in your scenario. Did it though?

i don't know for sure, the kde to enter the root password opened fine, i put my password and everything crashed/closed up, i don't remember any widget showing up after this

>The terminal output you have given looks incomplete to me. Are you sure that it is all you have gotten as output?
![Screenshot_20230124_195402](https://user-images.githubusercontent.com/72302817/214439228-bf7ef7af-fd22-414d-a286-906954302c3e.png)

same output

(i'm using wayland, don't know if it's important)

**Comment by Thenujan-0** [comment]
> (i'm using wayland, don't know if it's important)

Shouldn't be an issue.

The error message given by the program is not enough to get an idea about the bug. So are you okay with applying the patch i'm giving you to get a descriptive error message? if so proceed with the instructions below

First check if sha256sum of the file i'm going to change is exactly what i predicted. To do so run `sha256sum /opt/grub-editor/grub-editor.py` Check if the output is `09f46065432b1d28b95073962990b20cd66fcc7f0d48c3b4fe5e58de402889be  /opt/grub-editor/grub-editor.py
`

Download the patch file from https://drive.google.com/file/d/1Z7j2c6XDgaFAxod_1xJy5hYZQM3-TmPd/view?usp=sharing
then run `sudo patch /opt/grub-editor/grub-editor.py grub-editor.patch`
Note : patch file simply contains two print statements. You can see that yourself

Now run grub-editor.py through terminal again and provide the output

**Comment by ghost** [comment]
>First check if sha256sum of the file i'm going to change is exactly what i predicted

checksum match

<pre><code>-> % ./grub-editor.py 
starting main
/opt/grub-editor
Caught exception
Traceback (most recent call last):
  File "/opt/grub-editor/grubEditor/main.py", line 667, in set_comboBox_grub_default
    self.comboBox_grub_default.setCurrentIndex(self.all_entries.index(grub_default_val))
ValueError: '4' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/grub-editor/./grub-editor.py", line 66, in <module>
    main()
  File "/opt/grub-editor/grubEditor/main.py", line 1654, in main
    MainWindow=Ui()
  File "/opt/grub-editor/grubEditor/main.py", line 315, in __init__
    self.setUiElements(show_issues=True)
  File "/opt/grub-editor/grubEditor/main.py", line 776, in setUiElements
    self.set_comboBox_grub_default(show_invalid_default=show_issues)
  File "/opt/grub-editor/grubEditor/main.py", line 675, in set_comboBox_grub_default
    index = self.all_entries.index(from_number)
ValueError: 'Windows Boot Manager (on /dev/sdb2)' is not in list

python3 /opt/grub-editor/grubEditor/widgets/error_dialog.py 'An Exception occured' 'Traceback (most recent call last):
  File "/opt/grub-editor/grubEditor/main.py", line 667, in set_comboBox_grub_default
    self.comboBox_grub_default.setCurrentIndex(self.all_entries.index(grub_default_val))
ValueError: '4' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/grub-editor/./grub-editor.py", line 66, in <module>
    main()
  File "/opt/grub-editor/grubEditor/main.py", line 1654, in main
    MainWindow=Ui()
  File "/opt/grub-editor/grubEditor/main.py", line 315, in __init__
    self.setUiElements(show_issues=True)
  File "/opt/grub-editor/grubEditor/main.py", line 776, in setUiElements
    self.set_comboBox_grub_default(show_invalid_default=show_issues)
  File "/opt/grub-editor/grubEditor/main.py", line 675, in set_comboBox_grub_default
    index = self.all_entries.index(from_number)
ValueError: 'Windows Boot Manager (on /dev/sdb2)' is not in list
'
/bin/sh: -c: line 19: syntax error near unexpected token `('
/bin/sh: -c: line 19: `ValueError: 'Windows Boot Manager (on /dev/sdb2)' is not in list'
</code></pre>

**Comment by Thenujan-0** [comment]
Thank you for providing more information. I'm still not sure how the error occurs.
Can you provide the output of ` python3 /opt/grub-editor/grubEditor/libs/find_entries.py`

**Comment by Thenujan-0** [comment]
I have finally found the issue.
The issue is that UEFI Firmware settings should not be a submenu item of Windows boot manager.
Are you sure that your grub.cfg is not currupt?
Are you able to boot into windows, UEFI Firmware settings without any issues.
Can you provide the contents of /boot/grub/grub.cfg as well as /etc/default/grub

For a reference here is the output of `awk -F\' '$1=="menuentry " || $1=="submenu " {print i++ " : " $2}; /\tmenuentry / {print "\t" i-1">"j++ " : " $2};' /boot/grub/grub.cfg` In my machine.

```
0 : Manjaro Linux
1 : Advanced options for Manjaro Linux
        1>0 : Manjaro Linux (Kernel: 6.0.15-1-MANJARO x64)
        1>1 : Manjaro Linux (Kernel: 6.0.15-1-MANJARO x64 - fallback initramfs)
        1>2 : Manjaro Linux (Kernel: 5.15.85-1-MANJARO x64)
        1>3 : Manjaro Linux (Kernel: 5.15.85-1-MANJARO x64 - fallback initramfs)
2 : Windows Boot Manager (on /dev/nvme0n1p1)
3 : UEFI Firmware Settings
```
See how windows and UEFI settings are seen as Menu items and not submenu items

Can you run `sudo update-grub` and check the output of the awk command again

**Comment by Vilianexe** [comment]
> Are you sure that your grub.cfg is not currupt?

i don't know for sure, it's working fine, and i didn't see any error until now

**Comment by ghost** [comment]
>Are you sure that your grub.cfg is not currupt?

i don't know for sure, but i never run in any issues until now

>Are you able to boot into windows, UEFI Firmware settings without any issues.

yep, i've just tested it

>Can you provide the contents of /boot/grub/grub.cfg as well as /etc/default/grub

<pre><code>#
# DO NOT EDIT THIS FILE
#
# It is automatically generated by grub-mkconfig using templates
# from /etc/grub.d and settings from /etc/default/grub
#

### BEGIN /etc/grub.d/00_header ###
insmod part_gpt
insmod part_msdos
if [ -s $prefix/grubenv ]; then
  load_env
fi
if [ "${next_entry}" ] ; then
   set default="${next_entry}"
   set next_entry=
   save_env next_entry
   set boot_once=true
else
   set default="4"
fi

if [ x"${feature_menuentry_id}" = xy ]; then
  menuentry_id_option="--id"
else
  menuentry_id_option=""
fi

export menuentry_id_option

if [ "${prev_saved_entry}" ]; then
  set saved_entry="${prev_saved_entry}"
  save_env saved_entry
  set prev_saved_entry=
  save_env prev_saved_entry
  set boot_once=true
fi

function savedefault {
  if [ -z "${boot_once}" ]; then
    saved_entry="${chosen}"
    save_env saved_entry
  fi
}

function load_video {
  if [ x$feature_all_video_module = xy ]; then
    insmod all_video
  else
    insmod efi_gop
    insmod efi_uga
    insmod ieee1275_fb
    insmod vbe
    insmod vga
    insmod video_bochs
    insmod video_cirrus
  fi
}

if [ x$feature_default_font_path = xy ] ; then
   font=unicode
else
insmod part_gpt
insmod ext2
set root='hd0,gpt3'
if [ x$feature_platform_search_hint = xy ]; then
  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt3 --hint-efi=hd0,gpt3 --hint-baremetal=ahci0,gpt3  73243b3a-6c8a-4dd8-a2aa-a405aa347221
else
  search --no-floppy --fs-uuid --set=root 73243b3a-6c8a-4dd8-a2aa-a405aa347221
fi
    font="/usr/share/grub/unicode.pf2"
fi

if loadfont $font ; then
  set gfxmode=1280x720
  load_video
  insmod gfxterm
  set locale_dir=$prefix/locale
  set lang=en_US
  insmod gettext
fi
terminal_input console
terminal_output gfxterm
insmod part_gpt
insmod ext2
set root='hd0,gpt3'
if [ x$feature_platform_search_hint = xy ]; then
  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt3 --hint-efi=hd0,gpt3 --hint-baremetal=ahci0,gpt3  73243b3a-6c8a-4dd8-a2aa-a405aa347221
else
  search --no-floppy --fs-uuid --set=root 73243b3a-6c8a-4dd8-a2aa-a405aa347221
fi
insmod png
background_image -m stretch /usr/share/endeavouros/splash.png
if [ x$feature_timeout_style = xy ] ; then
  set timeout_style=menu
  set timeout=1
# Fallback normal timeout code in case the timeout_style feature is
# unavailable.
else
  set timeout=1
fi
### END /etc/grub.d/00_header ###

### BEGIN /etc/grub.d/10_linux ###
menuentry 'EndeavourOS Linux' --class endeavouros --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-simple-73243b3a-6c8a-4dd8-a2aa-a405aa347221' {
	load_video
	set gfxpayload=keep
	insmod gzio
	insmod part_gpt
	insmod ext2
	set root='hd0,gpt3'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt3 --hint-efi=hd0,gpt3 --hint-baremetal=ahci0,gpt3  73243b3a-6c8a-4dd8-a2aa-a405aa347221
	else
	  search --no-floppy --fs-uuid --set=root 73243b3a-6c8a-4dd8-a2aa-a405aa347221
	fi
	echo	'Loading Linux linux ...'
	linux	/boot/vmlinuz-linux root=UUID=73243b3a-6c8a-4dd8-a2aa-a405aa347221 rw  loglevel=0 nowatchdog nvme_load=YES
	echo	'Loading initial ramdisk ...'
	initrd	/boot/intel-ucode.img /boot/initramfs-linux.img
}
submenu 'Advanced options for EndeavourOS Linux' $menuentry_id_option 'gnulinux-advanced-73243b3a-6c8a-4dd8-a2aa-a405aa347221' {
	menuentry 'EndeavourOS Linux, with Linux linux' --class endeavouros --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-linux-advanced-73243b3a-6c8a-4dd8-a2aa-a405aa347221' {
		load_video
		set gfxpayload=keep
		insmod gzio
		insmod part_gpt
		insmod ext2
		set root='hd0,gpt3'
		if [ x$feature_platform_search_hint = xy ]; then
		  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt3 --hint-efi=hd0,gpt3 --hint-baremetal=ahci0,gpt3  73243b3a-6c8a-4dd8-a2aa-a405aa347221
		else
		  search --no-floppy --fs-uuid --set=root 73243b3a-6c8a-4dd8-a2aa-a405aa347221
		fi
		echo	'Loading Linux linux ...'
		linux	/boot/vmlinuz-linux root=UUID=73243b3a-6c8a-4dd8-a2aa-a405aa347221 rw  loglevel=0 nowatchdog nvme_load=YES
		echo	'Loading initial ramdisk ...'
		initrd	/boot/intel-ucode.img /boot/initramfs-linux.img
	}
	menuentry 'EndeavourOS Linux, with Linux linux (fallback initramfs)' --class endeavouros --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-linux-fallback-73243b3a-6c8a-4dd8-a2aa-a405aa347221' {
		load_video
		set gfxpayload=keep
		insmod gzio
		insmod part_gpt
		insmod ext2
		set root='hd0,gpt3'
		if [ x$feature_platform_search_hint = xy ]; then
		  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt3 --hint-efi=hd0,gpt3 --hint-baremetal=ahci0,gpt3  73243b3a-6c8a-4dd8-a2aa-a405aa347221
		else
		  search --no-floppy --fs-uuid --set=root 73243b3a-6c8a-4dd8-a2aa-a405aa347221
		fi
		echo	'Loading Linux linux ...'
		linux	/boot/vmlinuz-linux root=UUID=73243b3a-6c8a-4dd8-a2aa-a405aa347221 rw  loglevel=0 nowatchdog nvme_load=YES
		echo	'Loading initial ramdisk ...'
		initrd	/boot/intel-ucode.img /boot/initramfs-linux-fallback.img
	}
}

### END /etc/grub.d/10_linux ###

### BEGIN /etc/grub.d/20_linux_xen ###
### END /etc/grub.d/20_linux_xen ###

### BEGIN /etc/grub.d/30_os-prober ###
menuentry 'KDE neon 5.26 (22.04) (on /dev/sda1)' --class neon --class gnu-linux --class gnu --class os $menuentry_id_option 'osprober-gnulinux-simple-fd9b4a6c-ab77-45ef-9242-e77f34562160' {
	insmod part_gpt
	insmod ext2
	set root='hd0,gpt1'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt1 --hint-efi=hd0,gpt1 --hint-baremetal=ahci0,gpt1  fd9b4a6c-ab77-45ef-9242-e77f34562160
	else
	  search --no-floppy --fs-uuid --set=root fd9b4a6c-ab77-45ef-9242-e77f34562160
	fi
	linux /boot/vmlinuz-5.15.0-56-generic root=UUID=fd9b4a6c-ab77-45ef-9242-e77f34562160 ro quiet splash $vt_handoff
	initrd /boot/initrd.img-5.15.0-56-generic
}
submenu 'Advanced options for KDE neon 5.26 (22.04) (on /dev/sda1)' $menuentry_id_option 'osprober-gnulinux-advanced-fd9b4a6c-ab77-45ef-9242-e77f34562160' {
	menuentry 'Neon GNU/Linux (on /dev/sda1)' --class gnu-linux --class gnu --class os $menuentry_id_option 'osprober-gnulinux-/boot/vmlinuz-5.15.0-56-generic--fd9b4a6c-ab77-45ef-9242-e77f34562160' {
		insmod part_gpt
		insmod ext2
		set root='hd0,gpt1'
		if [ x$feature_platform_search_hint = xy ]; then
		  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt1 --hint-efi=hd0,gpt1 --hint-baremetal=ahci0,gpt1  fd9b4a6c-ab77-45ef-9242-e77f34562160
		else
		  search --no-floppy --fs-uuid --set=root fd9b4a6c-ab77-45ef-9242-e77f34562160
		fi
		linux /boot/vmlinuz-5.15.0-56-generic root=UUID=fd9b4a6c-ab77-45ef-9242-e77f34562160 ro quiet splash $vt_handoff
		initrd /boot/initrd.img-5.15.0-56-generic
	}
	menuentry 'Neon GNU/Linux, with Linux 5.15.0-56-generic (on /dev/sda1)' --class gnu-linux --class gnu --class os $menuentry_id_option 'osprober-gnulinux-/boot/vmlinuz-5.15.0-56-generic--fd9b4a6c-ab77-45ef-9242-e77f34562160' {
		insmod part_gpt
		insmod ext2
		set root='hd0,gpt1'
		if [ x$feature_platform_search_hint = xy ]; then
		  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt1 --hint-efi=hd0,gpt1 --hint-baremetal=ahci0,gpt1  fd9b4a6c-ab77-45ef-9242-e77f34562160
		else
		  search --no-floppy --fs-uuid --set=root fd9b4a6c-ab77-45ef-9242-e77f34562160
		fi
		linux /boot/vmlinuz-5.15.0-56-generic root=UUID=fd9b4a6c-ab77-45ef-9242-e77f34562160 ro quiet splash $vt_handoff
		initrd /boot/initrd.img-5.15.0-56-generic
	}
	menuentry 'Neon GNU/Linux, with Linux 5.15.0-53-generic (on /dev/sda1)' --class gnu-linux --class gnu --class os $menuentry_id_option 'osprober-gnulinux-/boot/vmlinuz-5.15.0-53-generic--fd9b4a6c-ab77-45ef-9242-e77f34562160' {
		insmod part_gpt
		insmod ext2
		set root='hd0,gpt1'
		if [ x$feature_platform_search_hint = xy ]; then
		  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt1 --hint-efi=hd0,gpt1 --hint-baremetal=ahci0,gpt1  fd9b4a6c-ab77-45ef-9242-e77f34562160
		else
		  search --no-floppy --fs-uuid --set=root fd9b4a6c-ab77-45ef-9242-e77f34562160
		fi
		linux /boot/vmlinuz-5.15.0-53-generic root=UUID=fd9b4a6c-ab77-45ef-9242-e77f34562160 ro quiet splash $vt_handoff
		initrd /boot/initrd.img-5.15.0-53-generic
	}
}

menuentry 'Windows Boot Manager (on /dev/sdb2)' --class windows --class os $menuentry_id_option 'osprober-efi-CCCF-A1C3' {
	insmod part_gpt
	insmod fat
	set root='hd1,gpt2'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-bios=hd1,gpt2 --hint-efi=hd1,gpt2 --hint-baremetal=ahci1,gpt2  CCCF-A1C3
	else
	  search --no-floppy --fs-uuid --set=root CCCF-A1C3
	fi
	chainloader /EFI/Microsoft/Boot/bootmgfw.efi
}
### END /etc/grub.d/30_os-prober ###

### BEGIN /etc/grub.d/30_uefi-firmware ###
if [ "$grub_platform" = "efi" ]; then
	fwsetup --is-supported
	if [ "$?" = 0 ]; then
		menuentry 'UEFI Firmware Settings' $menuentry_id_option 'uefi-firmware' {
			fwsetup
		}
	fi
fi
### END /etc/grub.d/30_uefi-firmware ###

### BEGIN /etc/grub.d/35_fwupd ###
### END /etc/grub.d/35_fwupd ###

### BEGIN /etc/grub.d/40_custom ###
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
### END /etc/grub.d/40_custom ###

### BEGIN /etc/grub.d/41_custom ###
if [ -f  ${config_directory}/custom.cfg ]; then
  source ${config_directory}/custom.cfg
elif [ -z "${config_directory}" -a -f  $prefix/custom.cfg ]; then
  source $prefix/custom.cfg
fi
### END /etc/grub.d/41_custom ###</code></pre>

<pre><code># GRUB boot loader configuration

GRUB_DEFAULT=4
GRUB_TIMEOUT=1
GRUB_DISTRIBUTOR="EndeavourOS"
GRUB_CMDLINE_LINUX_DEFAULT="loglevel=0 nowatchdog nvme_load=YES"
GRUB_CMDLINE_LINUX=""

# Preload both GPT and MBR modules so that they are not missed
GRUB_PRELOAD_MODULES="part_gpt part_msdos"

# Uncomment to enable booting from LUKS encrypted devices
#GRUB_ENABLE_CRYPTODISK=y

# Set to 'countdown' or 'hidden' to change timeout behavior,
# press ESC key to display menu.
GRUB_TIMEOUT_STYLE=menu

# Uncomment to use basic console
GRUB_TERMINAL_INPUT=console

# Uncomment to disable graphical terminal
#GRUB_TERMINAL_OUTPUT=console

# The resolution used on graphical terminal
# note that you can use only modes which your graphic card supports via VBE
# you can see them in real GRUB with the command `vbeinfo'
GRUB_GFXMODE=1280x720

# Uncomment to allow the kernel use the same resolution used by grub
GRUB_GFXPAYLOAD_LINUX=keep

# Uncomment if you want GRUB to pass to the Linux kernel the old parameter
# format "root=/dev/xxx" instead of "root=/dev/disk/by-uuid/xxx"
#GRUB_DISABLE_LINUX_UUID=true

# Uncomment to disable generation of recovery mode menu entries
GRUB_DISABLE_RECOVERY=true

# Uncomment and set to the desired menu colors.  Used by normal and wallpaper
# modes only.  Entries specified as foreground/background.
#GRUB_COLOR_NORMAL="light-blue/black"
#GRUB_COLOR_HIGHLIGHT="light-cyan/blue"

# Uncomment one of them for the gfx desired, a image background or a gfxtheme
#GRUB_BACKGROUND="/path/to/wallpaper"
#GRUB_THEME="/path/to/gfxtheme"
GRUB_BACKGROUND="/usr/share/endeavouros/splash.png"

# Uncomment to get a beep at GRUB start
#GRUB_INIT_TUNE="480 440 1"

# Uncomment to make GRUB remember the last selection. This requires
# setting 'GRUB_DEFAULT=saved' above.
#GRUB_SAVEDEFAULT=true

# Uncomment to disable submenus in boot menu
#GRUB_DISABLE_SUBMENU=true

# Probing for other operating systems is disabled for security reasons. Read
# documentation on GRUB_DISABLE_OS_PROBER, if still want to enable this
# functionality install os-prober and uncomment to detect and include other
# operating systems.
GRUB_DISABLE_OS_PROBER=false</code></pre>


>Can you run sudo update-grub and check the output of the awk command again

i use sudo grub-mkconfig -o /boot/grub/grub.cfg but running it don't change anything

>See how windows and UEFI settings are seen as Menu items and not submenu items

yep, i'm gonna search a bit and try to change it and run grub-editor again

**Comment by ghost** [comment]
if you send me your /etc/grub.d/30_uefi-firmware, to me, it's gonna work?

**Comment by ghost** [comment]
lol, i just deleted my 30_uefi-firmware and grub-editor opened fine

**Comment by Thenujan-0** [comment]
> if you send me your /etc/grub.d/30_uefi-firmware, to me, it's gonna work?
```
#! /bin/sh
set -e

# grub-mkconfig helper script.
# Copyright (C) 2020  Free Software Foundation, Inc.
#
# GRUB is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GRUB is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GRUB.  If not, see <http://www.gnu.org/licenses/>.

prefix="/usr"
exec_prefix="/usr"
datarootdir="/usr/share"

export TEXTDOMAIN=grub
export TEXTDOMAINDIR="${datarootdir}/locale"

. "$pkgdatadir/grub-mkconfig_lib"

EFI_VARS_DIR=/sys/firmware/efi/efivars
EFI_GLOBAL_VARIABLE=8be4df61-93ca-11d2-aa0d-00e098032b8c
OS_INDICATIONS="$EFI_VARS_DIR/OsIndicationsSupported-$EFI_GLOBAL_VARIABLE"

if [ -e "$OS_INDICATIONS" ] && \
   [ "$(( $(printf 0x%x \'"$(cat $OS_INDICATIONS | cut -b5)"\') & 1 ))" = 1 ]; then
  LABEL="UEFI Firmware Settings"

  gettext_printf "Adding boot menu entry for UEFI Firmware Settings ...\n" >&2

  cat << EOF
menuentry '$LABEL' \$menuentry_id_option 'uefi-firmware' {
	fwsetup
}
EOF
fi
```

**Comment by ghost** [comment]
yep everything is working now, and uefi firmware isn't the windows submenu anymore, thank you very much!
