### ISSUE TITLE
tries to launch, but quits

### ISSUE THREAD

**Issue by Hi-Phile** [Thenujan-0/grub-editor#2]
Not sure what other requirements are needed, but the installation went without any problems.  It might be the distribution or Window manager (RebornOS with Budgie Desktop).

I've noticed it seems to launch then immediately closes.

**Comment by Thenujan-0** [comment]
Thank you so much for reporting the issue can you please try running it from terminal and provide the output

**Comment by Thenujan-0** [comment]
It could be because a dependency issue . Can you install python-pyqt5 and then try opening it again. Or you can just reinstall the package from AUR. As i have updated the dependencies now

**Comment by Thenujan-0** [comment]
Closing this issue as OP didn't provide more information
