### ISSUE TITLE
installation from AUR missing dependency and will not launch even with dependency

### ISSUE THREAD

**Issue by letterlock** [Thenujan-0/grub-editor#3]
distribution: Manjaro
package installed from AUR with yay doesn't install PyQt5 but appears to succeed. throws following error upon running "__main__.py":
```
Traceback (most recent call last):
  File "/opt/grub-editor/./__main__.py", line 3, in <module>
    import main
  File "/opt/grub-editor/main.py", line 4, in <module>
    from PyQt5 import QtCore ,QtWidgets, uic,QtGui
ModuleNotFoundError: No module named 'PyQt5'
```
once i manually installed PyQt5 through pip, it instead throws this error:
```
starting main
Traceback (most recent call last):
  File "/opt/grub-editor/libs/find_entries.py", line 41, in <module>
    main_entries[-1].sub_entries.append(MainEntry(lines[i][7:],[]))
IndexError: list index out of range

list index out of range
error occured as an entry that was thought to be a sub entry couldnt be added to last main entry on the list .                  Error might have occured because the main_entries list is empty
adasd asdasd
exceas
2022-06-29 18:21:20,103 [ERROR] Unhandled exception: Traceback (most recent call last):
  File "/opt/grub-editor/main.py", line 784, in set_comboBox_grub_default
    self.comboBox_grub_default.setCurrentIndex(self.all_entries.index(grub_default_val))
ValueError: '0' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/grub-editor/./__main__.py", line 56, in <module>
    main_()
  File "/opt/grub-editor/./__main__.py", line 47, in main_
    main.main()
  File "/opt/grub-editor/main.py", line 1854, in main
    MainWindow=Ui()
  File "/opt/grub-editor/main.py", line 439, in __init__
    self.setUiElements(show_issues=True)
  File "/opt/grub-editor/main.py", line 897, in setUiElements
    self.set_comboBox_grub_default(show_invalid_default=show_issues)
  File "/opt/grub-editor/main.py", line 790, in set_comboBox_grub_default
    from_number =self.get_g_default_from_number(invalid_value)
  File "/opt/grub-editor/main.py", line 747, in get_g_default_from_number
    main_entry_obj = self.main_entries[int(g_default[0])]
IndexError: list index out of range
```

hope this is of some help, i'd love to have a replacement for grub-customizer that actually works with manjaro!

**Comment by rado84-github** [comment]
The dependency is python-pyqt5 and it's not in AUR, it's in Extra. Install it, then run the program again.

**Comment by Thenujan-0** [comment]
Thank you for reporting the issue.
Can you please provide the output of
```
 awk -F\' '$1=="menuentry " || $1=="submenu " {print i++ " : " $2}; /\tmenuentry / {print "\t" i-1">"j++ " : " $2};' /boot/grub/grub.cfg
```

**Comment by Thenujan-0** [comment]
python-pyqt5 has now been added as dependency in AUR package

**Comment by letterlock** [comment]
> Thank you for reporting the issue.
> Can you please provide the output of
> ```
>  awk -F\' '$1=="menuentry " || $1=="submenu " {print i++ " : " $2}; /\tmenuentry / {print "\t" i-1">"j++ " : " $2};' /boot/grub/grub.cfg
> ```

I'm not currently at my PC and won't be until next week, I'll be sure to run this when I get home if it's still relevant then. 

> The dependency is python-pyqt5 and it's not in AUR, it's in Extra. Install it, then run the program again.

wouldn't installing pyqt5 through pip satisfy the dependency? it seemed to me that the error was not to do with the dependency missing. if it helps, I can remove it and install it from the official repository instead, I'll do that when I get home as well, assuming the updated AUR package doesn't already provide the correct version.

**Comment by Thenujan-0** [comment]
> wouldn't installing pyqt5 through pip satisfy the dependency? it seemed to me that the error was not to do with the dependency missing. if it helps, I can remove it and install it from the official repository instead, I'll do that when I get home as well, assuming the updated AUR package doesn't already provide the correct version.

Based on the error you have recieved dependency is not the problem.The problem is on finding menu entries.

**Comment by letterlock** [comment]
alright:

fresh install from aur.

launching the program from its desktop entry in a menu doesn't work, launching the __main__.py file directly provides the following:
`starting main
Traceback (most recent call last):
  File "/opt/grub-editor/libs/find_entries.py", line 41, in <module>
    main_entries[-1].sub_entries.append(MainEntry(lines[i][7:],[]))
IndexError: list index out of range

list index out of range
error occured as an entry that was thought to be a sub entry couldnt be added to last main entry on the list .                  Error might have occured because the main_entries list is empty
adasd asdasd
exceas
2022-07-18 16:14:22,295 [ERROR] Unhandled exception: Traceback (most recent call last):
  File "/opt/grub-editor/main.py", line 784, in set_comboBox_grub_default
    self.comboBox_grub_default.setCurrentIndex(self.all_entries.index(grub_default_val))
ValueError: '0' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/grub-editor/./__main__.py", line 56, in <module>
    main_()
  File "/opt/grub-editor/./__main__.py", line 47, in main_
    main.main()
  File "/opt/grub-editor/main.py", line 1854, in main
    MainWindow=Ui()
  File "/opt/grub-editor/main.py", line 439, in __init__
    self.setUiElements(show_issues=True)
  File "/opt/grub-editor/main.py", line 897, in setUiElements
    self.set_comboBox_grub_default(show_invalid_default=show_issues)
  File "/opt/grub-editor/main.py", line 790, in set_comboBox_grub_default
    from_number =self.get_g_default_from_number(invalid_value)
  File "/opt/grub-editor/main.py", line 747, in get_g_default_from_number
    main_entry_obj = self.main_entries[int(g_default[0])]
IndexError: list index out of range`

however, running __main__.py as sudo seems to launch the program properly. i don't currently have time to test the program unfortunately, but hopefully that helps.

running the command you sent me gives me:
`awk: fatal: cannot open file `/boot/grub/grub.cfg' for reading: Permission denied`

so i ran it as sudo, whereupon it returned:
`0 : Manjaro Linux
1 : Advanced options for Manjaro Linux
	1>0 : Manjaro Linux (Kernel: 5.15.50-1-MANJARO x64)
	1>1 : Manjaro Linux (Kernel: 5.15.50-1-MANJARO x64 - fallback initramfs)
	1>2 : Manjaro Linux (Kernel: 4.19.249-1-MANJARO x64)
	1>3 : Manjaro Linux (Kernel: 4.19.249-1-MANJARO x64 - fallback initramfs)
2 : Windows Boot Manager (on /dev/nvme0n1p1)
3 : UEFI Firmware Settings`

hope this helps!

**Comment by Thenujan-0** [comment]
i thought /boot/grub/grub.cfg 's default permission would allow it to be read by the user. :thinking:  Are you sure you didn't change that file's permission?

**Comment by Thenujan-0** [comment]
In case you did. Simply changing the file permission to be readable by user should fix the issue

**Comment by letterlock** [comment]
i haven't manually changed it, so if something did change it i'm not aware of it... how strange. i'll change it to readable and give it a go. thanks for your help!

feel free to close this if you don't need any more information from me.

**Comment by Thenujan-0** [comment]
0c9a891cd61d5aa5c6aa73eab99a453f95e1d4a9  
Now a dialog pops up with the message when grub.cfg doesn't have read permissions
