### ISSUE TITLE
error mesg. 

### ISSUE THREAD

**Issue by hitobashira** [Thenujan-0/grub-editor#8]
Traceback (most recent call last):
  File "/opt/grub-editor/grubEditor/main.py", line 1162, in btn_set_callback
    self.saveConfsToCache()
  File "/opt/grub-editor/grubEditor/main.py", line 836, in saveConfsToCache
    initialize_temp_file(target_file_copy)
  File "/opt/grub-editor/grubEditor/main.py", line 80, in initialize_temp_file
    out = subprocess.check_output(["sha256sum", f"{CACHE_LOC}/temp.txt" , file_path]).decode()
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command [sha256sum,

System:
  Kernel: 6.1.6-zen1-1-zen arch: x86_64 bits: 64 compiler: gcc v: 12.2.0
    Desktop: Cinnamon v: 5.6.6 Distro: Manjaro Linux base: Arch Linux
Partition:
  ID-1: / size: 81.1 GiB used: 56.03 GiB (69.1%) fs: ext4 dev: /dev/nvme0n1p3
  ID-2: /boot/efi size: 998 MiB used: 103.6 MiB (10.4%) fs: vfat
    dev: /dev/nvme0n1p2
  ID-3: /home size: 1.34 TiB used: 787.64 GiB (57.6%) fs: btrfs
    dev: /dev/nvme0n1p10
  ID-4: /tmp size: 7.66 GiB used: 2.34 GiB (30.5%) fs: ext4 dev: /dev/zram1

**Comment by Thenujan-0** [comment]
Thank you for reporting the issue. Is this issue reproducible? ( happens again when you try what you were doing before when this error occured)

Can you also mention what you were doing when this error occured?
If this error occured when saving configurations, Is this the first time you are saving the configurations?

Can you also attach the log file at ~/.local/share/grub-editor/logs/main.log

**Comment by hitobashira** [comment]
It is the timing when the set button is pressed.
does not reproduce.

First use after installation.

It's a log file.
[main.log](https://github.com/Thenujan-0/grub-editor/files/10447177/main.log)

**Comment by Thenujan-0** [comment]
As you are saying that this does not reproduce, So the error didn't come back when you tried it again right?

**Comment by hitobashira** [comment]
yes.
now, I launch 3rd.
set 10 sec to 15 sec.
[set] autho...
....... save ssucessfullu. completed.

and snapshot tab.
create .
saved successfully.

**Comment by hitobashira** [comment]
Even if I close the app normally, it remains as a zombie.
I noticed it when shut down.
2 times in a row.

I can't capture it in English because it's about to shut down. This is Japanese.

It means a program that prevents shutdown.

Even the process was listed as zombie.

![Screenshot from 2023-01-20 11-01-31](https://user-images.githubusercontent.com/12706780/213645330-fa92bc42-9dc8-4d6f-a6ef-d403974090e9.png)

**Comment by Thenujan-0** [comment]
> Even if I close the app normally, it remains as a zombie. I noticed it when shut down. 2 times in a row.
> 
> I can't capture it in English because it's about to shut down. This is Japanese.
> 
> It means a program that prevents shutdown.
> 
> Even the process was listed as zombie.
> 
> ![Screenshot from 2023-01-20 11-01-31](https://user-images.githubusercontent.com/12706780/213645330-fa92bc42-9dc8-4d6f-a6ef-d403974090e9.png)

Can you create a seperate issue for this please?

**Comment by Thenujan-0** [comment]
Fixed on 7f933ec2e249fd076a3a1a24d93b77b081083d64
